micronaut:
  security:
    enabled: true
    token:
      name-key: "user_email"
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'dGVzdA=='
#              secret: "test"
              base64: true
              jws-algorithm: HS512


